[2024-04-14T10:03:02.450+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-14T10:03:02.488+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: hello_world.hello_world manual__2024-04-14T10:02:53.832953+00:00 [queued]>
[2024-04-14T10:03:02.503+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: hello_world.hello_world manual__2024-04-14T10:02:53.832953+00:00 [queued]>
[2024-04-14T10:03:02.504+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-04-14T10:03:02.529+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): hello_world> on 2024-04-14 10:02:53.832953+00:00
[2024-04-14T10:03:02.536+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=291) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-14T10:03:02.538+0000] {standard_task_runner.py:63} INFO - Started process 292 to run task
[2024-04-14T10:03:02.538+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'hello_world', 'hello_world', 'manual__2024-04-14T10:02:53.832953+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/hello_world.py', '--cfg-path', '/tmp/tmpa6ecku16']
[2024-04-14T10:03:02.541+0000] {standard_task_runner.py:91} INFO - Job 10: Subtask hello_world
[2024-04-14T10:03:02.601+0000] {task_command.py:426} INFO - Running <TaskInstance: hello_world.hello_world manual__2024-04-14T10:02:53.832953+00:00 [running]> on host 6d95d7b460cc
[2024-04-14T10:03:02.716+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='alexeevkv' AIRFLOW_CTX_DAG_ID='hello_world' AIRFLOW_CTX_TASK_ID='hello_world' AIRFLOW_CTX_EXECUTION_DATE='2024-04-14T10:02:53.832953+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-14T10:02:53.832953+00:00'
[2024-04-14T10:03:02.717+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-14T10:03:02.732+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-04-14T10:03:02.734+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'hello world!']
[2024-04-14T10:03:02.746+0000] {subprocess.py:86} INFO - Output:
[2024-04-14T10:03:02.749+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 1: hello: command not found
[2024-04-14T10:03:02.750+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2024-04-14T10:03:02.751+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-14T10:03:02.767+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2024-04-14T10:03:02.774+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=hello_world, task_id=hello_world, execution_date=20240414T100253, start_date=20240414T100302, end_date=20240414T100302
[2024-04-14T10:03:02.792+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 10 for task hello_world (Bash command failed. The command returned a non-zero exit code 127.; 292)
[2024-04-14T10:03:02.833+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-14T10:03:02.861+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-14T10:03:02.868+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
